services:
  app:
    build: .
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/voicechat
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: