services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/voicechat
      - DEV_MODE=true
      - ENABLE_LOGS=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - mongodb
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: